### ISSUE TITLE
Magisk Hide Toogle Keeps Reseting to "Disabled" for Isolated Process

### ISSUE THREAD

**Issue by jh0bc** [vvb2060/riru-unshare#1]
First, Thanks for the amazing module! :)

I'm using your module and it's working great with my bank's app's where one is using Isolated Process and another IBM Trusteer SDK for root detection.

Then I saw some reports on XDA about the app "Mandiri Online" detecting root using an Isolated Process.

So I did I little test with the combo Latest Magisk Canary + Riru Core v. 23.9 + Unshare Module but the app still detects root, I noticed something curious ... after I check the toggle for the isolated processes, he's getting reseted every time to "disabled" so because of this Magisk can't full hide root from him even with your module.
 
I don't know if this a issue of Magisk itself or from your module who enable handling the isolated process for Magisk or even a feature from the app

I'm opening this issue because when some other companies start doing the same thing (if this is a feature of this app) they can fully detect root again even with your module.

If you need any logs for further investigation please tell me.

Play Store Link: https://play.google.com/store/apps/details?id=com.bankmandiri.mandirionline

* The root detection is right after the start of the app with some toast msg and then he get killed

**Comment by vvb2060** [comment]
Try `magiskhide add isolated com.bankmandiri.mandirionline`

**Comment by vvb2060** [comment]
This issue will be fixed by Magisk

**Comment by jh0bc** [comment]
Many thanks for the very quick feedback! :)

Let's wait for the fix then

**Comment by Rob801130** [comment]
> su

**Comment by Rob801130** [comment]
`su
`

**Comment by jh0bc** [comment]
Hi! 

Issue with "Mandiri" app solved after the commit from the link below :

https://github.com/topjohnwu/Magisk/commit/68656521259bdf5b12c8d2a6177f6907dfc65f1a

Thanks! :)

But today I find another one with the same problem: 

https://play.google.com/store/apps/details?id=com.BanqueMisr.MobileBanking

Toogle for the isolated process keeps resetting 

Tried with latest Magisk Canary (22101) and Unshare 2.0

I checked the log of Magisk when adding the app to the Hide List and the main process appears just fine, but the isolated one don't show anything

@vvb2060
