### ISSUE TITLE
Isolated process are not displayed for certain apps

### ISSUE THREAD

**Issue by cawidtu** [vvb2060/riru-unshare#2]
I am not sure whether this is an issue with Magisk, riru-unshare or my Android version.

My configuration:

- Huawei Honor View 10 with MoKee ROM 20210309 (Android 9, variant of LineageOS 16)
 
- Magisk Canary 22005 (both app and binary)

- Riru 23.9
 
- Riru - Enhanced Mode for Magisk Hide v1.0

Magisk is able to display and hide isolated processes, but only for some apps. For example, the process com.darvin.security:tmpService of "Detect Magisk" (https://github.com/darvincisec/DetectMagiskHide) is displayed in Magisk Hide and can be hidden successfully. In contrast, only the main process of io.github.vvb2060.magiskdetector is displayed. Neither is the isolated process of the infamous Santander UK app displayed.

**Comment by vvb2060** [comment]
> Enable Enhanced mode for Magisk Hide. Allow Magisk Hide to handle isolated processes

Off topic, close.

**Comment by cawidtu** [comment]
![magisk](https://user-images.githubusercontent.com/17566729/111633424-c6fae200-87f5-11eb-8641-bc2b62877a61.png)

I am really sorry for being so intrusive, but I am not sure I made my point clear. Please see the attached screenshot. The isolated process of "DetectMagisk" is found but not of "MagiskDetector". What did I do wrong? I installed "Enable Enhanced mode for Magisk Hide" as stated in my original report.

**Comment by vvb2060** [comment]
`https://github.com/topjohnwu/Magisk/pull/4056/commits/3ed504d5a91b7771a3e26c7f555cf7b993551516`
