### ISSUE TITLE
Detect the number of "Magisk su processes"

### ISSUE THREAD

**Issue by Mark-Joy** [vvb2060/riru-unshare#6]
Sorry, I don't know whether or not this issue should be put here, but with riru-unshare is there a way to prevent the detection of "Magisk su processes" from magisk detector?
![Screenshot_2021-05-28-08-05-51-207_rikka riru](https://user-images.githubusercontent.com/22109528/119915061-dc298500-bf8b-11eb-88fb-4fe271b7cdf1.jpg)
![IMG_20210528_080700](https://user-images.githubusercontent.com/22109528/119915062-dd5ab200-bf8b-11eb-9dd5-c57b3bc540b9.jpg)

Some information:
Redmi Note 8 Pro
Android 9
Rom xiaomi.eu 11.0.2.0

Magisk 23
Riru 25.4.4
riru-unshare 2.0
Magisk detector 2.3

Magisk hide is enable.

**Comment by Rnager** [comment]
You can upgrade to Android Q+ (but make sure that SELinux is strict and there are no rules that allow and neverallow

**Comment by vvb2060** [comment]
`setenforce 1`
