### ISSUE TITLE
App launch delay after a reboot

### ISSUE THREAD

**Issue by jbro129** [vvb2060/riru-unshare#7]
I recently installed this module and noticed that there was a 5-10 second app launch delay whenever I try to open an app after a reboot. The only apps that I've noticed don't have a delay are apps that I've allowed to use root permissions.

My entire phone basically freezes pretty much. I have to either wait through the delay or press the home button to get back to my home screen.

My device is a Galaxy S20+ running android 11.
I am using the most recent Magisk and most recent Riru core.

**Comment by vvb2060** [comment]
Nothing to do with riru-unshare

**Comment by jbro129** [comment]
> Nothing to do with riru-unshare

How does this have nothing to do with riru-unshare? This issue only occurs on my device with the module installed and enabled. When I first noticed this issue I disabled the module and after that and a reboot the weird app launch delay was no longer there.

**Comment by vvb2060** [comment]
I believe this is caused by magiskhide, you may have checked too many applications.

**Comment by jbro129** [comment]
> I believe this is caused by magiskhide.

Even the apps that aren't selected to be hidden in magiskhide are having this delay.

Edit: I do have a lot of applications checked in magiskhide, but the fact that apps that aren't even checked are experiencing this is weird.
