### ISSUE TITLE
errors in define

### ISSUE THREAD

**Issue by haikejishu** [vvb2060/riru-unshare#9]
https://android.googlesource.com/platform/external/sepolicy/+/556bb0f55324e8839d7b735a0de9bc31028e839e/isolated_app.te

### and AID_ISOLATED_END (99999).

but the file 'android_filesystem_config.h'  is '#define AID_ISOLATED_START 90000'.

**Comment by yujincheng08** [comment]
https://cs.android.com/android/platform/superproject/+/master:system/core/libcutils/include/private/android_filesystem_config.h;l=210?q=AID_ISOLATED_START&sq=

**Comment by vvb2060** [comment]
@yujincheng08 https://android-review.googlesource.com/c/platform/system/core/+/873074

**Comment by haikejishu** [comment]
I know. Thanks @vvb2060 @yujincheng08
